### ISSUE TITLE
Cannot create new flight - Please enter flight duration as hours

### ISSUE THREAD

**Issue by sohantanna** [jpatokal/openflights#1481] opened 2024-07-15 20:25 UTC
Consistently getting this error:

> Please enter flight duration as hours and minutes with a colon between hour and minute, eg. 5:37 for 5 hours, 37 minutes. You can blank the duration to have it recalculated automatically.

**Comment by reedy** [comment] 2024-08-19 23:01
Dupe of #1449

**Closed as not planned by reedy** 2024-08-19 23:01 UTC
