### ISSUE TITLE
Allow a single trip to be over 24hrs for cruise/train travel

### ISSUE THREAD

**Issue by ThyPredator** [jpatokal/openflights#811] opened 2017-11-29 02:47 UTC
When trying to add a cruise voyage from a port to a port you can't manually put in a travel/sailing time of over 24hrs. This should be fixed. This should also be an option for cross continental rail journeys as well.
cheers
Tim

**Comment by reedy** [comment] 2023-03-01 02:34
Dupe of https://github.com/jpatokal/openflights/issues/83

**Closed as not planned by reedy** 2023-03-01 02:34 UTC
