### ISSUE TITLE
Tripit Connection bug

### ISSUE THREAD

**Issue by gehernando** [jpatokal/openflights#1444] opened 2023-10-03 19:43 UTC
I am not able to connect to tripit because even though I am logged it to tripit, it keeps telling me I need to sign in again:

https://www.loom.com/share/6fd8a1444c364e298adf024d9e3982c7?sid=1b022dae-57b8-4bf9-b646-62b31cba6ddb

**Comment by rhaig** [comment] 2023-10-04 15:07
duplicate of #1190

**Closed as not planned** 2023-10-09 17:17 UTC
