### ISSUE TITLE
KML Export contains no data

### ISSUE THREAD

**Issue by Stitch10925** [jpatokal/openflights#1036] opened 2020-07-31 19:08 UTC
When exporting to KML the main XML structure is in the file, but it contains no data. As a result, when I import it into Google Earth, there is nothing there.

I tried by searching for Amsterdam (Schiphol), then listing all the flights, then export to KLM.

**Comment by chrisrosset** [comment] 2023-07-12 00:19
Duplicate of #156.

**Closed as not planned by chrisrosset** 2023-07-12 00:19 UTC
Labels: bug
