### ISSUE TITLE
Add DAY OF WEEK to filtering capability

### ISSUE THREAD

**Issue by dannygrad** [jpatokal/openflights#477] opened 2016-02-28 20:31 UTC
Hi guys:

Is it possible to add DAY OF WEEK filtering to the capabilities please?

Thanks,

Dan

**Comment by chrisrosset** [comment] 2023-11-11 01:56
Duplicate of https://github.com/jpatokal/openflights/issues/296.

**Closed as not planned by chrisrosset** 2023-11-11 01:56 UTC
Labels: enhancement
