### ISSUE TITLE
Flight time issue

### ISSUE THREAD

**Issue by sohantanna** [jpatokal/openflights#1453] opened 2023-11-13 14:35 UTC
Getting this error adding flights:

Please enter flight duration as hours and minutes with a colon between hour and minute, eg. 5:37 for 5 hours, 37 minutes. You can blank the duration to have it recalculated automatically.

Even though the time is blank

**Comment by reedy** [comment] 2023-11-18 14:09
Dupe of #1449

**Closed as not planned by reedy** 2023-11-18 14:09 UTC
Labels: bug
