### ISSUE TITLE
List flights not working

### ISSUE THREAD

**Issue by benmacd80** [jpatokal/openflights#1101] opened 2022-10-21 00:06 UTC
Whenever I click on list flights for all, or for 2022, I just a spiral animated circle with no flights listed below. For 2021 and earlier, it works no problem.

Perhaps there is a data corruption somewhere in my flight data? User is superben

Thanks.

**Comment by jhuldtgren** [comment] 2022-10-27 23:00
I'm seeing this behavior too (fwiw, both on nginx.openflights.org and www.openflights.org). In my case trying to list "All" or the year 2017 results in just loading. All other years I can load just fine. Interestingly when I pick 2017 the map works and if I click on each airport loading that subset works just fine for every airport but all of 2017 will not. 

I have CSV exports of my data and nothing looks weird about 2017, and as far as I can recall I've not edited any of my 2017 flights, since well 2017 when I put them in. 

my username is the same as my username here.

**Comment by benmacd80** [comment] 2022-10-28 14:28
I backed up the data to CSV, deleted all my flights, and attempted to import the CSV and I get an '_**upload failed**_' error.

My username is superben, now with 0 flights.

**Comment by jpatokal** [comment] 2022-10-29 07:18
@benmacd80 Uploads are now fixed, but that was a separate issue.  If you can figure out which flights are causing the problem, can you either attach the CSV here or mail to me directly at info(at)openflights.org?

**Comment by jhuldtgren** [comment] 2022-10-29 12:06
@jpatokal To clarify what I wrote above, trying to list all flights results in a hang, trying to list the year 2017 results in a hang. All other years can be listed correctly, so in my case it's some flight in 2017 which is causing an issue. However as it's only list which hangs setting the filter to 2017 filters the map to only show the flights from 2017, I can then click on each airport and list the flights to and from it I took in 2017, doing that and comparing it to the export shows I can list each flight from 2017, so I'm not sure why individually it seems to work but trying to list 2017 in total fails. 

In case it helps I can say everything was working on September 9th, when I entered my previous flight and exported the results. 

I can send you an export if that'll help.

**Comment by mccnash** [comment] 2022-11-13 12:37
I have the same issue. List flights doesnt work when set to all carries all years.
If i go through the year selection it is only 2022 which doesnt work. so i can use the button for every other year but 2022. 2022 results in an endless spinning circle and no list is loaded however the map itself changes.

THis also happens when i select just specific airlines but all years. for example i am not able to select AA or DL when set to all years. 

However, if I set the year to 2022 and AA or 2022 and DL i can see the flights.  I edited a couple flights where information of AA was missing due to this bug., which i wasn't able to until i just found this work around by showing only certain years or airlines. Now i can select all years and AA works now when i select that carrier. 


Unfortunately all my DL flights for 2022 already have all the information filled out. I opened them up anyway, edited some stuff so i can use the save button but still when i set to all years and just DL, i cant show the list.

Something strange is going on. as the data is all there. The maps will update accordingly even when I select a combination which doesnt list any flights. Hope this helps....

**Comment by 2sylbl** [comment] 2022-11-15 16:15
Having the same issue here. Seems that some flight info being 'undefined' is blocking the List Flights from completing. These have been in my list for ages without issue (I fixed one from 2011 by re-adding the airline code, this latest one is from 2010). Will report back if I can fix this one.

<img width="1403" alt="openflights-undefined" src="https://user-images.githubusercontent.com/21063547/201969380-523f0c3b-a2d8-4888-9bc1-531cd28b0f81.png">

**Comment by 2sylbl** [comment] 2022-11-15 16:22
> Having the same issue here. Seems that some flight info being 'undefined' is blocking the List Flights from completing. These have been in my list for ages without issue (I fixed one from 2011 by re-adding the airline code, this latest one is from 2010). Will report back if I can fix this one.
> 

When I originally opened the flight with 'undefined' data up for editing, the 'Carrier' field had 'American Airlines' with no (AA) after it. I replaced it with the auto-fill option for American Airlines (AA) and saved it. It's still erroring out at the same location (but I recall that when I fixed the previous one from 2011 it also took some time before the List Flights would proceed past that one - maybe db sync takes a while?)

<img width="459" alt="openflights-undefined2" src="https://user-images.githubusercontent.com/21063547/201972121-b6cda2a4-0398-4ecb-9678-c3ecfb0e39d9.png">

**Comment by 2sylbl** [comment] 2022-11-18 14:34
@jpatokal After fixing the 2 data issues (one in 2011, one in 2010), List Flights now hangs completely for me if I choose to list All years/All carriers, or the year 2011 with All carriers. 2007/All Carriers also seems to hang. Any other combination (including any specific carrier in 2007 or 2011) seems to work fine. So I'm not sure what data could be causing this hang now.  My user name is dennypayne if that helps.

**Comment by jpatokal** [comment] 2022-12-04 07:01
Unfortunately I have not been able to replicate this locally.  Could somebody seeing this issue please send a CSV export of your flights, ideally the smallest set that shows the issue, to info at openflights.org?

**Comment by gneissone** [comment] 2022-12-09 15:08
I am also experiencing this issue with listing 2022 (or all) flights. Not sure if it helps, but here's what I see in the console.

<img width="1478" alt="Screen Shot 2022-12-09 at 10 08 16 AM" src="https://user-images.githubusercontent.com/10748475/206732369-34476298-d363-4f5b-aecc-1fccbaccf2db.png">

@jpatokal Happy to send my data if you think it will help, but as others have mentioned, if I filter by airline in addition to year, I'm able to see all my data in the list (isolated by airline of course).

**Comment by 2sylbl** [comment] 2022-12-09 15:46
> Unfortunately I have not been able to replicate this locally. Could somebody seeing this issue please send a CSV export of your flights, ideally the smallest set that shows the issue, to info at openflights.org?

@jpatokal I just sent an original and edited one to you.

**Comment by 2sylbl** [comment] 2023-01-24 20:50
FWIW, List all flights no longer seems to be hanging for me. However, if I select year 2011 it still hangs there.

**Comment by jhuldtgren** [comment] 2023-01-25 01:52
> FWIW, List all flights no longer seems to be hanging for me. However, if I select year 2011 it still hangs there.

Unfortunately I've seen no change in behavior, both 2017 and all still hang.

**Comment by ConciergeKey** [comment] 2023-02-11 19:33
FINALLY - I FINALLY UN-EFFED MY FLIGHT HISTORY!  

I spent two hours manipulating my Master Backup CSV file on a second account, importing and deleting and changing, etc., etc.  I thought the issue was to do with a bunch of different things, but nothing was consistent.  I caught a break when I found that deleting all of the non-required data resulted in a working version that would list all flights.  I then narrowed it down to the "Note" field - if I deleted all Notes then it worked fine.  I thought it had to do with commas or other special characters in the Notes field, but after painstaking troubleshooting, that wasn't the issue at all.

The problem causing the hanging is a character length being exceeded in the Notes field!  One of my more recent flights (the one that broke it) had a description that was 51 characters long.  I don't know what the limit is set to, but shortening it to be under 50 seemed to do the trick.  I don't think it's to do with the raw count of characters in the Notes field... it may aggregate with something else to trip an overall limit.  But, regardless, try shortening up your longest descriptions and you may be back in business.

What an ordeal!  Now I have to go add in all my flights for the last 6 months!

**Comment by 2sylbl** [comment] 2023-02-16 18:48
I'm back to hanging on all flights now too 👎 

I tried ConciergeKey's suggestion for the 2011 flights I have since that's the year it doesn't seem to like, but so far it's still hanging on all flights or that year.

**Comment by 2sylbl** [comment] 2023-02-16 21:54
I note that I can still export a full CSV from the settings page, even with List flights still hanging. I was having some success with specifying a specific carrier when listing the 2011 year - it would list everything there. I just made an edit to an American Airlines flight in that year and now AA/2011 combination hangs. I added a registration and a short note to an existing record. All other carriers still function. So I suspect the issue is confined to my AA 2011 records somehow, but I don't see anything in the CSV that stands out as a problem.

**Comment by 2sylbl** [comment] 2023-02-28 14:44
After this latest round of fixes that showed up today, this issue seems to be solved now. I have tried various combinations that used to hang up and they all work now. Hopefully this sticks :-)

**Comment by jhuldtgren** [comment] 2023-02-28 19:42
i noticed about a week ago that both "all" and "2017" were loading for me. Very glad issue seems to have been resolved.

**Comment by ConciergeKey** [comment] 2023-02-28 20:07
I'm so happy it seems to be fixed across the board now!

**Comment by jpatokal** [comment] 2023-03-01 00:35
Awesome, calling this fixed.  Huge props to @reedy for figuring out and fixing the issue, I thought this was due to the data itself but it was a nginx config problem!

**Closed as completed by jpatokal** 2023-03-01 00:35 UTC
