### ISSUE TITLE
Total mileage showing only in KM despite my settings being miles

### ISSUE THREAD

**Issue by jamesrkunz** [jpatokal/openflights#1120] opened 2022-11-21 03:28 UTC
Everything else is in miles, e.g. my Top 10, journey records, etc. but my total mileage, cumulatively and for each year, is in kilometers. Pleasehelp!

**Comment by reedy** [comment] 2022-12-02 00:39
Dupe of https://github.com/jpatokal/openflights/issues/1111

**Comment by jpatokal** [comment] 2022-12-04 06:23
Closing as duplicate.

**Closed as completed by jpatokal** 2022-12-04 06:23 UTC
