### ISSUE TITLE
Cant Sync with Tripit

### ISSUE THREAD

**Issue by CamShep69** [jpatokal/openflights#1489] opened 2024-11-13 07:49 UTC
I am a new Openflights user.  I click on Import, select Tripit and the pop-up window goes blank - nothing happens.  I tried on Chrome and Edge.  Thanks.

**Comment by reedy** [comment] 2024-11-25 17:55
It's almost certainly a dupe of https://github.com/jpatokal/openflights/issues/1178

And/or https://github.com/jpatokal/openflights/issues/1190

**Closed as not planned by reedy** 2024-11-25 17:55 UTC
