### ISSUE TITLE
CSV Import ignores Duration

### ISSUE THREAD

**Issue by JtheP** [jpatokal/openflights#334] opened 2015-07-09 18:38 UTC
I finally decided to try the CSV import and it works very well, but the tool ignores duration and calculates based on the route.  

Here's what's in my CSV file (note I entered 00:45):

![csv_example](https://cloud.githubusercontent.com/assets/13260094/8603701/f2f50e00-2647-11e5-910d-bd44d039b475.jpg)

And here's what showed up in my Flight List (note it converted to 00:48)

![openflight_record](https://cloud.githubusercontent.com/assets/13260094/8603727/1b1b82c4-2648-11e5-8a40-0d5c91613614.jpg)

Thanks!

**Comment by reedy** [comment] 2023-03-01 02:18
Dupe of https://github.com/jpatokal/openflights/issues/162

**Closed as not planned by reedy** 2023-03-01 02:18 UTC
