### ISSUE TITLE
Ghost Airport

### ISSUE THREAD

**Issue by Kowalzky** [jpatokal/openflights#993] opened 2019-10-05 08:43 UTC
When I do an analysis on my data set, FOA is reported as northernmost visited airport.
I have no record containing this airport in my data. northernmost should be LED

**Comment by leezbtv** [comment] 2022-08-09 17:00
Interestingly, I've encountered this same issue where FOA appears as my new northernmost airport after taking my first trip to OSL, having never flown to FOA. Previously it had been EDI, which was fine.

**Comment by chrisrosset** [comment] 2023-07-12 01:43
I have been able to reproduce this with OSL. Key insight: OpenFlights lists OSL and FOA  as having the same latitude 60.121.

It's caused by an oversight in [the SQL query](https://github.com/jpatokal/openflights/blob/9a3fa289755e1067c60f3f66136eb12395a7c44e/php/stats.php#L112) which first finds the max latitude and then grabs a matching airport. Except that it can grab the wrong one if there is more than one.

No luck with LED but the data might have been updated since. I believe it's the same issue still.

**Comment by chrisrosset** [comment] 2023-07-13 00:06
Reproduced on dev with a single flight:

![ghost-airport](https://github.com/jpatokal/openflights/assets/1103294/a01ea451-cddf-4564-9ce3-dbe11b3bab12)

**Comment by chrisrosset** [comment] 2023-07-13 01:08
The fix is waiting for #1317 to be merged.

**Comment by chrisrosset** [comment] 2023-07-13 03:58
I believe the change also fixes #119.

**Comment by reedy** [comment] 2023-07-13 18:02
> I believe the change also fixes #119.

I'd be curious if you still see that issue on a much newer mysql/mariadb...

Either way, #1317 merged, hopefully without causing much conflict to your patch if you want to post it for review

**Closed as completed** 2023-07-14 23:30 UTC
Labels: bug
