### ISSUE TITLE
Possible mishandling of session credentials

### ISSUE THREAD

**Issue by tmpuserforbugreport** [jpatokal/openflights#646] opened 2016-12-22 15:37 UTC
Hello!

I met that situation several times before but last time I was able to take a screenshot. If I open some flight details from the List of flights and then leave that flight details open for some time (probably more than 30 minutes) and press 'Exit' button, the site returns me to the list of flights, but this list is populated with arbitrary data. On the screenshot attached you may see that exact situation: the map shows my flights, but the list contains some garbage (WOW to WOW) and flights that I definitely did not go (e.g. Santiago, Chile (SCL) to Mount Pleasant, Falkland Islands (Islas Malvinas) (MPN)).

![tmp](https://cloud.githubusercontent.com/assets/24719162/21430505/bd2d3300-c863-11e6-8e7c-8c1ddb7b6bcc.png)

**Comment by chrisrosset** [comment] 2023-07-12 01:06
This data is not arbitrary - it's the demo data you see when you open the website. This works as designed even if it's not great design...

Duplicate of #23.

**Closed as not planned by chrisrosset** 2023-07-12 01:06 UTC
Labels: bug
